-- Create tables

-- 1. books
CREATE TABLE books (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    book_name text NOT NULL,
    product_code text,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

-- 2. songs
CREATE TABLE songs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    book_id bigint REFERENCES books(id) ON DELETE SET NULL,
    song_name text NOT NULL,
    grade text,
    memo text,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

-- 3. artists
CREATE TABLE artists (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Artist_name" text NOT NULL
);

-- 4. lyricists
CREATE TABLE lyricists (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lyricist_name text NOT NULL
);

-- 5. songwriters
CREATE TABLE songwriters (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    song_writer_name text NOT NULL
);

-- 6. arrangers
CREATE TABLE arrangers (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    arranger_name text NOT NULL
);

-- Association Tables

-- 7. song_artist_association
CREATE TABLE song_artist_association (
    song_id bigint REFERENCES songs(id) ON DELETE CASCADE NOT NULL,
    artist_id bigint REFERENCES artists(id) ON DELETE CASCADE NOT NULL,
    PRIMARY KEY (song_id, artist_id)
);

-- 8. song_lyricist_association
CREATE TABLE song_lyricist_association (
    song_id bigint REFERENCES songs(id) ON DELETE CASCADE NOT NULL,
    lyricist_id bigint REFERENCES lyricists(id) ON DELETE CASCADE NOT NULL,
    PRIMARY KEY (song_id, lyricist_id)
);

-- 9. song_writer_association
CREATE TABLE song_writer_association (
    song_id bigint REFERENCES songs(id) ON DELETE CASCADE NOT NULL,
    song_writer_id bigint REFERENCES songwriters(id) ON DELETE CASCADE NOT NULL,
    PRIMARY KEY (song_id, song_writer_id)
);

-- 10. song_arranger_association
CREATE TABLE song_arranger_association (
    song_id bigint REFERENCES songs(id) ON DELETE CASCADE NOT NULL,
    arranger_id bigint REFERENCES arrangers(id) ON DELETE CASCADE NOT NULL,
    PRIMARY KEY (song_id, arranger_id)
);

-- Indexes for performance (Partial matching optimization usually needs pg_trgm but simple btree works for prefix/equality)
CREATE INDEX idx_songs_book_id ON songs(book_id);
CREATE INDEX idx_songs_name ON songs(song_name);
CREATE INDEX idx_books_name ON books(book_name);
